# Generated by Django 5.2.4 on 2025-07-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movielink',
            index=models.Index(fields=['source_type'], name='idx_movie_links_source_type'),
        ),
    ]
